id: P0BA8D19A
initial_creation_type: input
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: bo
  volumes:
    177bb9d47f724f398566b54566e1dc63:
      title: Complete text
      base_file: Complete text.txt
      work_id: W884AA4A1
  chapter_to_tile: {}
created_at: '2022-03-02T09:08:00.606116'
last_modified_at: '2022-03-02T09:08:00.606137'
